### ISSUE TITLE
Consider a flatter structure for the menu

### ISSUE THREAD

**Issue by karenmajewicz** [OpenGeoMetadata/opengeometadata.github.io#36]
Idea for making this easier to navigate:

- Home
As we add more pages in the future, we may want a flatter navigation structure for this site. Here is a possible layout:

- Get started

- Current Schema (just the index)
  - Title
  - Alternative title
  - etc.

- Legacy Versions
  - 1.0
  - 0.5

- OGM Metadata Guides
  - About OGM Aardvark (most of the info currently on the Current Schema page)
  - JSON format 
  - Fields
  - References
  - Writing Metadata
  - Publishing in Solr
  - Upgrading
- Helpful Resources
  - Workflow examples
  - Scripts and tools
  - Further Reading

**Comment by rmseifried** [comment]
To-do items from the Google Doc referenced above:

- [ ] Keith: experiment with repo directory  hierarchy and header hierarchy labels - is it possible for all pages to exist in the same folder (docs) so that internal links are easier to write?
- [ ] Move “OGM Aardvark” to “Current Schema Index” and fix internal links - the goal is for users to click on “Current Schema” and be taken immediately to the schema table
- [ ] Move “Current Schema index” to a new page that won’t be in the TOC, but will be linked as a button at the top of the new “Current Schema Index”, rename to something like “About Aardvark”. This is more of an informational page than a guide or resource.
- [ ] Move “Upgrade” to under Helpful Resources and add a button at the top of the new “Current Schema Index” to point to it.
- [ ] Decide how to deal with the OGM Metadata Guides and Helpful Resources (ideas: combine into a single page; combine into a single page and then hide apart from the TOC / link as a button on the Current Schema Index; move whole section into the main menu and keep essentially as is)

**Comment by rmseifried** [comment]
Related issue: https://github.com/OpenGeoMetadata/metadata-issues/issues/42

**Comment by karenmajewicz** [comment]
see new PR #68
