### ISSUE TITLE
Breadcrumbs not working

### ISSUE THREAD

**Issue by rmseifried** [OpenGeoMetadata/opengeometadata.github.io#72]
## Problem

At the top of each field page, there is an auto-generated navigation menu (breadcrumbs) with a clickable link to return to "OGM Aardvark." Clicking this link keeps the user on the same page.

<img width="684" alt="Screen Shot 2023-01-31 at 11 17 43 AM" src="https://user-images.githubusercontent.com/36506059/215818728-25f9f1f8-101b-458f-9800-7bae6c7d1334.png">

## Expected behavior

Clicking this link should return the user to the schema landing page (https://opengeometadata.org/docs/ogm-aardvark).

**Comment by rmseifried** [comment]
I suspect we may need to upgrade the Just the Docs version. See: https://just-the-docs.github.io/just-the-docs/MIGRATION/#v033--v04x

**Comment by karenmajewicz** [comment]
I propose we switch over to using mkdocs.org, which is what we use for geoblacklight.org/docs. 

It's pretty similar - we still write things in Markdown and we can still have the same readthedocs template. However, it uses a python framework instead of jekyll (ruby) to compile to Markdown into HTML. Overall, I find it much simpler to use.

**Comment by rmseifried** [comment]
Fixed by https://github.com/OpenGeoMetadata/opengeometadata.github.io/pull/80
