### ISSUE TITLE
Aardvark Rights in-page link doesn't work

### ISSUE THREAD

**Issue by mradamcox** [OpenGeoMetadata/opengeometadata.github.io#88]
At the top of the [Aardvark document](https://opengeometadata.org/ogm-aardvark), the Rights item links to `#rights`, which you would expect to work but doesn't. Looks like for whatever reason, the anchor for the Rights section is `#rights_1`, https://opengeometadata.org/ogm-aardvark/#rights_1.

Just wanted to raise this issue because a deeper look into why `rights_1` exists may be nice, but another way to handle it is just change the link at the top of the page.

**Comment by karenmajewicz** [comment]
The problem seems to be that we also have a "Rights Holder" field on the page.  The anchor link for that is #rights-holder, but the "-" is not being treated as a character, so "Rights" and "Rights Holder" are somehow interpreted as duplicates.

I made a PR that does what @mradamcox suggests - just change the link in the top table to "#rights_1". (I am not sure if this is the right way to fix it long term, but I couldn't figure out a better solution.)
